### PR TITLE
Use component-clone and component-type for browsers support

### PR DESCRIPTION
**Pull request by cristiandouce**
`Array.isArray` is not supported x-browser. So I used `component/type` and `component/clone`.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks!

**Comment by cristiandouce** [comment]
:dancer:

**Comment by dy** [comment]
@cristiandouce I have a conceptual concern. I have a doubt related to using `component/type` to polyfill the environment. Why not to leave that task to polyfills?

**Comment by cristiandouce** [comment]
@dfcreative Polyfills are ok when you can control the environment. For example, in your own service or webapp.

When you expect your compiled (and public) component to be included or embeded in different environments, this approach is better IMHO. Mostly to avoid strange or erratic behaviors when polyfills may vary according to the host environment.

If you want to ensure that it will work no matter where it is included, wrappers like `component/type` are best choice. Otherwise polyfills are just fine! :grinning:

It could be left to polyfills as you say. Yet, there is the need to instruct in that "required" dependency for it to correctly work across environments. Won't you say?

**Pull request merged**
